"""Add collection tables

Revision ID: 2b4c1f8a7d2e
Revises: 
Create Date: 2025-08-05 23:05:00.108620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b4c1f8a7d2e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('overview', sa.String(), nullable=True),
    sa.Column('poster_url', sa.String(), nullable=True),
    sa.Column('backdrop_url', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('runtime', sa.Integer(), nullable=True),
    sa.Column('monitored', sa.Boolean(), nullable=True),
    sa.Column('downloaded', sa.Boolean(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movies_id'), 'movies', ['id'], unique=False)
    op.create_index(op.f('ix_movies_title'), 'movies', ['title'], unique=False)
    op.create_index(op.f('ix_movies_tmdb_id'), 'movies', ['tmdb_id'], unique=True)
    op.create_table('tv_shows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('overview', sa.String(), nullable=True),
    sa.Column('poster_url', sa.String(), nullable=True),
    sa.Column('backdrop_url', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('monitored', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tv_shows_id'), 'tv_shows', ['id'], unique=False)
    op.create_index(op.f('ix_tv_shows_title'), 'tv_shows', ['title'], unique=False)
    op.create_index(op.f('ix_tv_shows_tmdb_id'), 'tv_shows', ['tmdb_id'], unique=True)
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('show_id', sa.Integer(), nullable=True),
    sa.Column('season_number', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('overview', sa.String(), nullable=True),
    sa.Column('poster_url', sa.String(), nullable=True),
    sa.Column('monitored', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['show_id'], ['tv_shows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seasons_id'), 'seasons', ['id'], unique=False)
    op.create_index(op.f('ix_seasons_tmdb_id'), 'seasons', ['tmdb_id'], unique=True)
    op.create_table('episodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('episode_number', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('overview', sa.String(), nullable=True),
    sa.Column('air_date', sa.String(), nullable=True),
    sa.Column('monitored', sa.Boolean(), nullable=True),
    sa.Column('downloaded', sa.Boolean(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_episodes_id'), 'episodes', ['id'], unique=False)
    op.create_index(op.f('ix_episodes_tmdb_id'), 'episodes', ['tmdb_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_episodes_tmdb_id'), table_name='episodes')
    op.drop_index(op.f('ix_episodes_id'), table_name='episodes')
    op.drop_table('episodes')
    op.drop_index(op.f('ix_seasons_tmdb_id'), table_name='seasons')
    op.drop_index(op.f('ix_seasons_id'), table_name='seasons')
    op.drop_table('seasons')
    op.drop_index(op.f('ix_tv_shows_tmdb_id'), table_name='tv_shows')
    op.drop_index(op.f('ix_tv_shows_title'), table_name='tv_shows')
    op.drop_index(op.f('ix_tv_shows_id'), table_name='tv_shows')
    op.drop_table('tv_shows')
    op.drop_index(op.f('ix_movies_tmdb_id'), table_name='movies')
    op.drop_index(op.f('ix_movies_title'), table_name='movies')
    op.drop_index(op.f('ix_movies_id'), table_name='movies')
    op.drop_table('movies')
    # ### end Alembic commands ###
