"""add_file_tracking_fields

Revision ID: 3a2a2d7c35e6
Revises: 2b4c1f8a7d2e
Create Date: 2025-08-05 21:17:44.576247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a2a2d7c35e6'
down_revision = '2b4c1f8a7d2e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_paths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_paths_id'), 'media_paths', ['id'], unique=False)
    op.add_column('episodes', sa.Column('runtime', sa.Integer(), nullable=True))
    op.add_column('episodes', sa.Column('file_path', sa.String(), nullable=True))
    op.add_column('episodes', sa.Column('file_name', sa.String(), nullable=True))
    op.add_column('episodes', sa.Column('file_size', sa.BigInteger(), nullable=True))
    op.add_column('episodes', sa.Column('quality', sa.String(), nullable=True))
    op.add_column('episodes', sa.Column('release_group', sa.String(), nullable=True))
    op.add_column('tv_shows', sa.Column('folder_path', sa.String(), nullable=True))
    op.add_column('tv_shows', sa.Column('total_size', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tv_shows', 'total_size')
    op.drop_column('tv_shows', 'folder_path')
    op.drop_column('episodes', 'release_group')
    op.drop_column('episodes', 'quality')
    op.drop_column('episodes', 'file_size')
    op.drop_column('episodes', 'file_name')
    op.drop_column('episodes', 'file_path')
    op.drop_column('episodes', 'runtime')
    op.drop_index(op.f('ix_media_paths_id'), table_name='media_paths')
    op.drop_table('media_paths')
    # ### end Alembic commands ###
