"""add_config_settings_table

Revision ID: 5018bf9dae6c
Revises: 6d2c78546363
Create Date: 2025-08-07 22:24:50.507846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5018bf9dae6c'
down_revision = '6d2c78546363'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_config_settings_id'), 'config_settings', ['id'], unique=False)
    op.create_index(op.f('ix_config_settings_key'), 'config_settings', ['key'], unique=True)
    op.create_index(op.f('ix_config_settings_section'), 'config_settings', ['section'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_config_settings_section'), table_name='config_settings')
    op.drop_index(op.f('ix_config_settings_key'), table_name='config_settings')
    op.drop_index(op.f('ix_config_settings_id'), table_name='config_settings')
    op.drop_table('config_settings')
    # ### end Alembic commands ###
