"""add_monitoring_option_field

Revision ID: 6d2c78546363
Revises: 4b5c2f9a8e3f
Create Date: 2025-08-07 21:35:47.570554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d2c78546363'
down_revision = '4b5c2f9a8e3f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tv_shows', sa.Column('monitoring_option', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tv_shows', 'monitoring_option')
    # ### end Alembic commands ###
